remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Sarah Downs
author: sarahdowns409
email: sdowns@ucmerced.edu
description: > # this means to ignore newlines until "baseurl:"
PhD Student in Applied Math. DOD SMART Scholar. Machine Learning, Optimization, and Fluid Dyanamics.

# social links
github_username:  sarahdowns409

show_excerpts: true # set to false to remove excerpts on the homepage
